# Mod Info
modName = Enhanced Mob Spawners
modId = spawnermod
modGroup = com.branders.spawnermod
modVersion = 1.0.0

# Minecraft & Forge versions
minecraftVersion = 1.7.10
forgeVersion = 10.13.4.1614

# MCP mappings
channel = stable
mappingsVersion = 12
remoteMappings = https\://raw.githubusercontent.com/MinecraftForge/FML/1.7.10/conf/

# Dev environment
developmentEnvironmentUserName = Dev

# Disable Mixins (not needed for this mod)
usesMixins = false

# Proxy settings (use your local proxy)
systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=7897
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=7897
